### ISSUE TITLE
Occasional timeout failures

### ISSUE THREAD

**Issue by Sparrow0hawk** [Sparrow0hawk/police-api-client-python#1]
This is a note to remind me to add more details of this issue.

**Comment by Sparrow0hawk** [comment]
Ran pytest locally three times, 1/3 get the following HTTP 500 error
```
=================================================== FAILURES ===================================================
__________________________________ [doctest] police_api.stop_and_search.Stop ___________________________________
010     guaranteed to be provided by forces, so take care around any ``None``
011     values you may encounter.
012 
013     .. doctest::
014 
015         >>> from police_api import PoliceAPI
016         >>> api = PoliceAPI(timeout=30)
017         >>> def sort_stops_by_date(unsorted_stops):
018         ...     return(sorted(unsorted_stops, key=lambda s: s.datetime))
019         >>> stops = sort_stops_by_date(
UNEXPECTED EXCEPTION: APIError()
Traceback (most recent call last):
  File "/Users/alexcoleman/PhD_OneDrive/Code/Forks/police-api-client-python/police_api/service.py", line 22, in raise_for_status
    request.raise_for_status()
  File "/Users/alexcoleman/anaconda3/envs/policeapi/lib/python3.6/site-packages/requests-2.24.0-py3.6.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://data.police.uk/api/stops-force?force=metropolitan&date=2018-07
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/alexcoleman/anaconda3/envs/policeapi/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)
  File "<doctest police_api.stop_and_search.Stop[3]>", line 2, in <module>
  File "/Users/alexcoleman/PhD_OneDrive/Code/Forks/police-api-client-python/police_api/__init__.py", line 394, in get_stops_force
    'GET', 'stops-force', force=force.id, date=date, **kwargs)]
  File "/Users/alexcoleman/PhD_OneDrive/Code/Forks/police-api-client-python/police_api/service.py", line 47, in request
    return self._make_request(verb.upper(), url, kwargs)
  File "/Users/alexcoleman/PhD_OneDrive/Code/Forks/police-api-client-python/police_api/service.py", line 42, in _make_request
    self.raise_for_status(r)
  File "/Users/alexcoleman/PhD_OneDrive/Code/Forks/police-api-client-python/police_api/service.py", line 24, in raise_for_status
    raise APIError(e)
police_api.exceptions.APIError: <unknown error code>
/Users/alexcoleman/PhD_OneDrive/Code/Forks/police-api-client-python/police_api/stop_and_search.py:19: UnexpectedException
=========================================== short test summary info ============================================
FAILED police_api/stop_and_search.py::police_api.stop_and_search.Stop
```
